---

- hosts: local
  gather_facts: false

  vars:
          conteneurs:
                  - squashtm
                  - mariadb-1
                  - mariadb-2
                  - proxy

  tasks:
          - name: Deploy containers
            docker_container:
                    name: "{{ item }}"
                    hostname: "{{ item }}"
                    image: debian-ansible:stretch
                    state: started
                    tty: yes
                    pull: no
            loop: "{{ conteneurs }}"

          - name: Get informations on container
            docker_container_info:
                    name: "{{ item }}"
            register: "resultat"
            loop: "{{ conteneurs }}"

          - name: Print container informations
            debug: 
              msg: "Hostname: {{ item.container.Config.Hostname }} ; IP: {{ item.container.NetworkSettings.IPAddress }}"
            when: item.exists
            loop: "{{ resultat.results }}"
